[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip",
  "/app/.venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["/app/.venv/bin/python manage.py collectstatic --noinput"]